# -*- coding: utf-8 -*-
"""1_feature_transform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1atWO4tjimAUlVk11JLdjdxudQxIi9y4y
"""

# -*- coding: utf-8 -*-
"""1_featurestransform (canonical basin-consistent rewrite)

Colab-oriented script to build canonical feature tables for:
1) Station-level training/validation
2) Basin-level prediction

Design decisions implemented:
- Primary canonical basin key: hydrobasin_level12
- HYBAS_ID kept as mapping/QC field
- Monthly discharge/watertemp via nearest-cell extraction at canonical basin supportpoint
- QC/provenance exported separately from canonical ML predictors
- Model-ready feature set = exact overlap of transferable predictors between station and basin tables
- Global + Europe outputs
"""

from google.colab import drive
drive.mount('/content/drive')

#!/usr/bin/env python3
import os
import warnings
from typing import Iterable

import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
from shapely.geometry import Point, LineString, MultiLineString
from sklearn.neighbors import BallTree


warnings.filterwarnings("ignore", category=UserWarning)

# =====================================================
# FEATURE FILTERING + READABLE LABELS
# =====================================================
NON_PREDICTOR_EXACT = {
    "HYBAS_ID", "hydrobasin_level12", "geometry",
    "NEXT_DOWN", "NEXT_SINK", "MAIN_BAS", "PFAF_ID", "SORT", "ORDER",
    "DIST_SINK", "DIST_MAIN", "SUB_AREA", "UP_AREA", "ENDO", "COAST",
    "supportpoint_method", "support_stream_order", "continent_tile",
    "country_name", "country_name_obs", "wqms_id", "wqms_lat", "wqms_lon",
    "hydrobasin_level12_obs", "hydrobasin_level12_spatial", "HYBAS_ID_spatial",
    "qc_has_obs_key", "qc_has_spatial_key", "qc_obs_vs_spatial_key_mismatch",
    "qc_primary_vs_hybasid_mismatch", "qc_primary_vs_hybasid_mismatch_basin",
    "qc_hybasid_from_basin", "gad_id_smj",
}

NON_PREDICTOR_CLASS_CODES = {
    "clz_cl_smj", "cls_cl_smj", "glc_cl_smj", "pnv_cl_smj", "wet_cl_smj",
    "tbi_cl_smj", "tec_cl_smj", "fmh_cl_smj", "fec_cl_smj", "lit_cl_smj",
}

NON_PREDICTOR_PREFIXES = ("qc_", "prov_")


def is_model_predictor_column(column: str) -> bool:
    c = str(column).strip()
    if c in NON_PREDICTOR_EXACT or c in NON_PREDICTOR_CLASS_CODES:
        return False
    if c.startswith(NON_PREDICTOR_PREFIXES):
        return False
    if c.endswith("_id") or "_id_" in c.lower():
        return False
    if re.search(r"_cl_", c):
        return False
    return True


BASE_LABELS = {
    "dis_m3": "Natural river discharge",
    "run_mm": "Runoff depth",
    "inu_pc": "Inundated area",
    "lka_pc": "Lake area",
    "lkv_mc": "Lake volume",
    "rev_mc": "Reservoir volume",
    "dor_pc": "Degree of river regulation",
    "ria_ha": "River area",
    "riv_tc": "River volume",
    "gwt_cm": "Groundwater table depth",
    "ele_mt": "Elevation",
    "slp_dg": "Terrain slope",
    "sgr_dk": "Stream gradient",
    "tmp_dc": "Air temperature",
    "pre_mm": "Precipitation",
    "pet_mm": "Potential evapotranspiration",
    "aet_mm": "Actual evapotranspiration",
    "ari_ix": "Aridity index",
    "cmi_ix": "Climate moisture index",
    "snw_pc": "Snow cover",
    "glc_pc": "Land-cover fraction",
    "pnv_pc": "Potential natural vegetation fraction",
    "wet_pc": "Wetland fraction",
    "for_pc": "Forest cover",
    "crp_pc": "Cropland cover",
    "pst_pc": "Pasture cover",
    "ire_pc": "Irrigated area",
    "gla_pc": "Glacier cover",
    "prm_pc": "Permafrost extent",
    "pac_pc": "Protected area coverage",
    "cly_pc": "Soil clay fraction",
    "slt_pc": "Soil silt fraction",
    "snd_pc": "Soil sand fraction",
    "soc_th": "Soil organic carbon",
    "swc_pc": "Soil water content",
    "kar_pc": "Karst area",
    "ero_kh": "Soil erosion",
    "pop_ct": "Population count",
    "ppd_pk": "Population density",
    "urb_pc": "Urban area",
    "nli_ix": "Night-time lights index",
    "rdd_mk": "Road density",
    "hft_ix": "Human footprint index",
    "gdp_ud": "Gross domestic product",
    "hdi_ix": "Human Development Index",
    "dist_to_wwtp_km": "Distance to nearest wastewater treatment plant",
    "discharge": "Monthly discharge at basin support point",
    "watertemp": "Monthly water temperature at basin support point",
}

UNITS = {
    "dis_m3": "m3/s", "run_mm": "mm/yr", "inu_pc": "%", "lka_pc": "%",
    "lkv_mc": "million m3", "rev_mc": "million m3", "dor_pc": "%",
    "ria_ha": "ha", "gwt_cm": "cm", "ele_mt": "m", "slp_dg": "degrees",
    "tmp_dc": "0.1 deg C", "pre_mm": "mm", "pet_mm": "mm", "aet_mm": "mm",
    "snw_pc": "%", "glc_pc": "%", "pnv_pc": "%", "wet_pc": "%",
    "for_pc": "%", "crp_pc": "%", "pst_pc": "%", "ire_pc": "%",
    "gla_pc": "%", "prm_pc": "%", "pac_pc": "%", "cly_pc": "%",
    "slt_pc": "%", "snd_pc": "%", "swc_pc": "%", "urb_pc": "%",
    "ppd_pk": "people/km2", "dist_to_wwtp_km": "km",
}

SUFFIX_LABELS = {
    "syr": "annual value in sub-basin",
    "uyr": "annual value for upstream catchment",
    "sav": "average in sub-basin",
    "uav": "average for upstream catchment",
    "smn": "minimum in sub-basin",
    "umn": "minimum for upstream catchment",
    "smx": "maximum in sub-basin",
    "umx": "maximum for upstream catchment",
    "slt": "long-term low value in sub-basin",
    "ult": "long-term low value for upstream catchment",
    "sse": "share in sub-basin",
    "use": "share for upstream catchment",
    "ssu": "sum in sub-basin",
    "usu": "sum for upstream catchment",
    "pyr": "annual average",
    "pmn": "minimum monthly average",
    "pmx": "maximum monthly average",
    "pva": "variability indicator",
    "sg1": "class 1 in sub-basin",
    "ug1": "class 1 for upstream catchment",
    "sg2": "class 2 in sub-basin",
    "ug2": "class 2 for upstream catchment",
}

LAND_COVER_CLASSES = {
    **{f"s{i:02d}": f"class {i:02d} in sub-basin" for i in range(1, 23)},
    **{f"u{i:02d}": f"class {i:02d} for upstream catchment" for i in range(1, 23)},
}
MONTH_SUFFIXES = {f"s{i:02d}": f"month {i:02d} in sub-basin" for i in range(1, 13)}
MONTH_SUFFIXES.update({f"u{i:02d}": f"month {i:02d} for upstream catchment" for i in range(1, 13)})


def split_hydroatlas_code(feature: str) -> tuple[str, str | None]:
    f = str(feature)
    for suffix in sorted(set(SUFFIX_LABELS) | set(LAND_COVER_CLASSES) | set(MONTH_SUFFIXES), key=len, reverse=True):
        token = "_" + suffix
        if f.endswith(token):
            return f[: -len(token)], suffix
    return f, None


def feature_label(feature: str, include_code: bool = True) -> str:
    raw = str(feature)
    base, suffix = split_hydroatlas_code(raw)
    base_label = BASE_LABELS.get(base, raw.replace("_", " "))

    if suffix is None:
        label = base_label
    elif base in {"pre_mm", "pet_mm", "aet_mm", "tmp_dc", "snw_pc", "cmi_ix", "discharge", "watertemp"} and suffix in MONTH_SUFFIXES:
        label = f"{base_label}, {MONTH_SUFFIXES[suffix]}"
    elif base in {"glc_pc", "pnv_pc", "wet_pc"} and suffix in LAND_COVER_CLASSES:
        label = f"{base_label}, {LAND_COVER_CLASSES[suffix]}"
    else:
        suffix_label = SUFFIX_LABELS.get(suffix) or LAND_COVER_CLASSES.get(suffix) or MONTH_SUFFIXES.get(suffix)
        label = f"{base_label}, {suffix_label}" if suffix_label else base_label

    unit = UNITS.get(base)
    if unit:
        label = f"{label} [{unit}]"
    if include_code:
        label = f"{label} ({raw})"
    return label



# =====================================================
# CONFIG
# =====================================================
BASE = "/content/drive/MyDrive/SamuelRebel_thesis/T2"

# Inputs
STATIONS_CSV = f"{BASE}/data/wq_data/wqms_site_info.csv"
OBS_FOLDER = f"{BASE}/output/observations/mean_test"  # optional for station↔basin QC enrichment
HW_CSV = f"{BASE}/data/HydroWASTE_v10.csv"

PATH_DISCHARGE = f"{BASE}/data/discharge_monthAvg_2010_2019.nc"
PATH_WATERTEMP = f"{BASE}/data/waterTemp_monthAvg_2010_2019.nc"

# Basin/HydroAtlas
ATLAS_FILE = f"{BASE}/data/predictor_data/BasinAtlas/ShapeFiles/BasinATLAS_v10_lev12.shp"

# HydroBASINS tiles (for station join + Europe mask + key QC)
CONTINENTS = {
    "Africa": "hybas_af",
    "Asia": "hybas_as",
    "SouthAmerica": "hybas_sa",
    "NorthAmerica": "hybas_na",
    "Europe": "hybas_eu",
    "Oceania": "hybas_au",
    "Greenland": "hybas_gr",
    "Siberia": "hybas_si",
    "Arctic": "hybas_ar",
}
CONTINENTS_BASE = f"{BASE}/data/predictor_data"

# RiverATLAS for supportpoint/outlet logic
RIVER_DIR = f"{BASE}/data/RiverATLAS_v10_shp"

# Outputs
OUT_DIR = f"{BASE}/output"


EUROPE_COUNTRIES = {
    "Albania", "Andorra", "Armenia", "Austria", "Azerbaijan", "Belarus", "Belgium",
    "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Cyprus", "Czechia", "Czech Republic",
    "Denmark", "Estonia", "Finland", "France", "Georgia", "Germany", "Greece", "Hungary",
    "Iceland", "Ireland", "Italy", "Kazakhstan", "Kosovo", "Latvia", "Liechtenstein",
    "Lithuania", "Luxembourg", "Malta", "Moldova", "Monaco", "Montenegro",
    "Netherlands", "North Macedonia", "Republic of Macedonia", "Norway", "Poland", "Portugal",
    "Romania", "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden",
    "Switzerland", "Turkey", "Ukraine", "United Kingdom", "Vatican City",
}

PRIMARY_KEY = "hydrobasin_level12"
SECONDARY_KEY = "HYBAS_ID"


# =====================================================
# HELPERS
# =====================================================
def _safe_key(s: pd.Series) -> pd.Series:
    s = s.astype("string").str.strip()
    s = s.str.replace(r"\.0$", "", regex=True)
    return s


def ensure_primary_key(df: pd.DataFrame,
                       primary_key: str = PRIMARY_KEY,
                       secondary_key: str = SECONDARY_KEY) -> pd.DataFrame:
    out = df.copy()
    if primary_key not in out.columns:
        if secondary_key in out.columns:
            out[primary_key] = out[secondary_key]
        else:
            out[primary_key] = pd.NA
    out[primary_key] = _safe_key(out[primary_key])

    if secondary_key in out.columns:
        out[secondary_key] = _safe_key(out[secondary_key])
    return out


def sanitize_columns(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out.columns = (
        out.columns
        .str.strip()
        .str.replace(r"[^\w]+", "_", regex=True)
        .str.replace(r"_+", "_", regex=True)
        .str.strip("_")
    )
    out = out.loc[:, ~out.columns.duplicated()]
    return out


def haversine_km(lat1, lon1, lat2, lon2):
    r = 6371.0088
    lat1 = np.deg2rad(lat1)
    lon1 = np.deg2rad(lon1)
    lat2 = np.deg2rad(lat2)
    lon2 = np.deg2rad(lon2)
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat / 2.0) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2.0) ** 2
    return 2.0 * r * np.arcsin(np.sqrt(a))


def normalize_lon_to_grid(lons: np.ndarray, grid_lons: np.ndarray) -> np.ndarray:
    """Align point longitudes to netCDF longitude convention (-180..180 or 0..360)."""
    lons = np.asarray(lons, dtype=float).copy()
    gmin = float(np.nanmin(grid_lons))
    gmax = float(np.nanmax(grid_lons))

    if gmin >= 0 and gmax > 180:
        lons = np.mod(lons, 360.0)
    elif gmin < 0 and gmax <= 180:
        lons = ((lons + 180.0) % 360.0) - 180.0
    return lons


def nearest_index(sorted_vals: np.ndarray, targets: np.ndarray) -> np.ndarray:
    idx = np.searchsorted(sorted_vals, targets, side="left")
    idx = np.clip(idx, 1, len(sorted_vals) - 1)
    left = sorted_vals[idx - 1]
    right = sorted_vals[idx]
    idx -= (np.abs(targets - left) < np.abs(targets - right))
    return idx


def select_linestring(geom):
    if geom is None or geom.is_empty:
        return None
    if isinstance(geom, LineString):
        return geom
    if isinstance(geom, MultiLineString):
        parts = [g for g in geom.geoms if isinstance(g, LineString) and not g.is_empty]
        if not parts:
            return None
        return max(parts, key=lambda g: g.length)
    return None


def read_obs_station_context(obs_folder: str) -> pd.DataFrame:
    if not os.path.isdir(obs_folder):
        return pd.DataFrame(columns=["wqms_id", PRIMARY_KEY, "country_name"])

    files = [os.path.join(obs_folder, f) for f in os.listdir(obs_folder) if f.endswith(".csv")]
    if not files:
        return pd.DataFrame(columns=["wqms_id", PRIMARY_KEY, "country_name"])

    rows = []
    for f in files:
        try:
            tmp = pd.read_csv(f, usecols=lambda c: c in {"wqms_id", PRIMARY_KEY, "country_name"})
            rows.append(tmp)
        except Exception:
            continue

    if not rows:
        return pd.DataFrame(columns=["wqms_id", PRIMARY_KEY, "country_name"])

    obs_ctx = pd.concat(rows, ignore_index=True)
    obs_ctx = ensure_primary_key(obs_ctx)

    # Most frequent basin/country per station for robust reference mapping
    def mode_or_nan(s):
        s = s.dropna()
        if s.empty:
            return pd.NA
        return s.mode().iloc[0]

    return (
        obs_ctx.groupby("wqms_id", as_index=False)
        .agg({PRIMARY_KEY: mode_or_nan, "country_name": mode_or_nan})
        .rename(columns={PRIMARY_KEY: f"{PRIMARY_KEY}_obs", "country_name": "country_name_obs"})
    )


def read_hydrobasins_tiles() -> gpd.GeoDataFrame:
    pieces = []
    for continent, basename in CONTINENTS.items():
        shp = f"{CONTINENTS_BASE}/{continent}/{basename}_lev12_v1c.shp"
        if not os.path.exists(shp):
            print(f"⚠️ HydroBASINS tile missing: {shp}")
            continue

        gdf = gpd.read_file(shp)
        if gdf.crs is None:
            gdf = gdf.set_crs("EPSG:4326")
        else:
            gdf = gdf.to_crs("EPSG:4326")

        keep = [c for c in ["HYBAS_ID", "geometry"] if c in gdf.columns]
        gdf = gdf[keep].copy()
        gdf["continent_tile"] = continent
        gdf = ensure_primary_key(gdf)
        pieces.append(gdf)

    if not pieces:
        raise FileNotFoundError("Geen HydroBASINS tiles gevonden. Controleer CONTINENTS_BASE.")

    out = pd.concat(pieces, ignore_index=True)
    out = gpd.GeoDataFrame(out, geometry="geometry", crs="EPSG:4326")
    out = out.drop_duplicates(subset=[PRIMARY_KEY], keep="first")
    return out


def read_basinatlas() -> gpd.GeoDataFrame:
    atlas = gpd.read_file(ATLAS_FILE)
    if atlas.crs is None:
        atlas = atlas.set_crs("EPSG:4326")
    else:
        atlas = atlas.to_crs("EPSG:4326")

    atlas = ensure_primary_key(atlas)
    atlas = sanitize_columns(atlas)

    # Re-ensure keys after sanitization
    atlas = ensure_primary_key(atlas)
    atlas = atlas.drop_duplicates(subset=[PRIMARY_KEY], keep="first")
    return atlas


def read_stations() -> gpd.GeoDataFrame:
    st = pd.read_csv(STATIONS_CSV)
    st = st.dropna(subset=["wqms_lat", "wqms_lon"]).copy()
    st = ensure_primary_key(st)

    stg = gpd.GeoDataFrame(
        st,
        geometry=gpd.points_from_xy(st["wqms_lon"], st["wqms_lat"]),
        crs="EPSG:4326"
    )
    return stg


def assign_stations_to_basins(stations_gdf: gpd.GeoDataFrame,
                              hydrobasins_gdf: gpd.GeoDataFrame,
                              obs_ctx: pd.DataFrame) -> pd.DataFrame:
    st_join = gpd.sjoin(
        stations_gdf,
        hydrobasins_gdf[[PRIMARY_KEY, SECONDARY_KEY, "continent_tile", "geometry"]],
        how="left",
        predicate="within",
        lsuffix="st",
        rsuffix="hb",
    ).drop(columns=["index_right"], errors="ignore")

    def _pick_col(cols: list[str], base: str, prefer_right: bool = True) -> str | None:
        ordered = [
            f"{base}_hb",
            f"{base}_right",
            base,
            f"{base}_st",
            f"{base}_left",
        ] if prefer_right else [
            base,
            f"{base}_st",
            f"{base}_left",
            f"{base}_hb",
            f"{base}_right",
        ]
        for c in ordered:
            if c in cols:
                return c
        return None

    key_src = _pick_col(list(st_join.columns), PRIMARY_KEY, prefer_right=True)
    hyb_src = _pick_col(list(st_join.columns), SECONDARY_KEY, prefer_right=True)

    st_join[f"{PRIMARY_KEY}_spatial"] = st_join[key_src] if key_src is not None else pd.NA
    st_join[f"{SECONDARY_KEY}_spatial"] = st_join[hyb_src] if hyb_src is not None else pd.NA
    st_join[f"{PRIMARY_KEY}_spatial"] = _safe_key(st_join[f"{PRIMARY_KEY}_spatial"])
    st_join[f"{SECONDARY_KEY}_spatial"] = _safe_key(st_join[f"{SECONDARY_KEY}_spatial"])

    st_df = pd.DataFrame(st_join.drop(columns="geometry", errors="ignore"))
    st_df = st_df.merge(obs_ctx, on="wqms_id", how="left")

    # Canonical primary key decision: prefer obs key when available, else spatial key
    st_df[PRIMARY_KEY] = st_df[f"{PRIMARY_KEY}_obs"].where(st_df[f"{PRIMARY_KEY}_obs"].notna(), st_df[f"{PRIMARY_KEY}_spatial"])
    st_df[PRIMARY_KEY] = _safe_key(st_df[PRIMARY_KEY])

    # Keep HYBAS_ID as mapping/QC field (from spatial basin assignment)
    st_df[SECONDARY_KEY] = _safe_key(st_df.get(f"{SECONDARY_KEY}_spatial", pd.Series(index=st_df.index, dtype="string")))

    # Country fallback
    if "country_name" not in st_df.columns:
        st_df["country_name"] = pd.NA
    st_df["country_name"] = st_df["country_name"].where(st_df["country_name"].notna(), st_df.get("country_name_obs", pd.Series(index=st_df.index, dtype="string")))

    # QC flags
    st_df["qc_has_obs_key"] = st_df[f"{PRIMARY_KEY}_obs"].notna()
    st_df["qc_has_spatial_key"] = st_df[f"{PRIMARY_KEY}_spatial"].notna()
    st_df["qc_obs_vs_spatial_key_mismatch"] = (
        st_df[f"{PRIMARY_KEY}_obs"].notna()
        & st_df[f"{PRIMARY_KEY}_spatial"].notna()
        & (st_df[f"{PRIMARY_KEY}_obs"] != st_df[f"{PRIMARY_KEY}_spatial"])
    )
    st_df["qc_primary_vs_hybasid_mismatch"] = (
        st_df[PRIMARY_KEY].notna()
        & st_df[SECONDARY_KEY].notna()
        & (st_df[PRIMARY_KEY] != st_df[SECONDARY_KEY])
    )

    return st_df


def read_riveratlas() -> gpd.GeoDataFrame:
    if not os.path.isdir(RIVER_DIR):
        print(f"⚠️ RiverATLAS directory not found: {RIVER_DIR}")
        return gpd.GeoDataFrame(columns=["geometry", "ORD_STRA"], crs="EPSG:4326")

    shp_files = [os.path.join(RIVER_DIR, f) for f in os.listdir(RIVER_DIR)
                 if f.startswith("RiverATLAS_v10_") and f.endswith(".shp")]
    shp_files = sorted(shp_files)
    if not shp_files:
        print("⚠️ No RiverATLAS shapefiles found.")
        return gpd.GeoDataFrame(columns=["geometry", "ORD_STRA"], crs="EPSG:4326")

    pieces = []
    for shp in shp_files:
        gdf = gpd.read_file(shp)
        if gdf.crs is None:
            gdf = gdf.set_crs("EPSG:4326")
        else:
            gdf = gdf.to_crs("EPSG:4326")

        keep = [c for c in ["ORD_STRA", "geometry"] if c in gdf.columns]
        gdf = gdf[keep].copy()
        pieces.append(gdf)

    out = pd.concat(pieces, ignore_index=True)
    out = gpd.GeoDataFrame(out, geometry="geometry", crs="EPSG:4326")
    out["ORD_STRA"] = pd.to_numeric(out.get("ORD_STRA", pd.Series(np.nan, index=out.index)), errors="coerce")
    return out


def derive_basin_supportpoints(
    basin_gdf: gpd.GeoDataFrame,
    river_gdf: gpd.GeoDataFrame,
) -> gpd.GeoDataFrame:
    """
    Supportpoint hierarchy per basin:
    1) outlet proxy from dominant river segment endpoint near basin boundary
    2) dominant river midpoint fallback
    3) polygon representative point fallback
    """
    bas = basin_gdf[[PRIMARY_KEY, SECONDARY_KEY, "geometry"]].copy()
    bas = bas.dropna(subset=["geometry", PRIMARY_KEY]).copy()

    if len(river_gdf) == 0:
        pts = bas.copy()
        pts["supportpoint_method"] = "centroid_fallback"
        pts["support_stream_order"] = np.nan
        pts["qc_snap_dist_km_river"] = np.nan
        pts["geometry"] = pts.geometry.representative_point()
        return pts

    bas_m = bas.to_crs("EPSG:3035")
    riv_m = river_gdf.to_crs("EPSG:3035")
    riv_m = riv_m[~riv_m.geometry.is_empty & riv_m.geometry.notna()].copy()
    riv_m["line_len_m"] = riv_m.geometry.length

    joined = gpd.sjoin(
        riv_m[["ORD_STRA", "line_len_m", "geometry"]],
        bas_m[[PRIMARY_KEY, SECONDARY_KEY, "geometry"]],
        how="inner",
        predicate="intersects"
    ).drop(columns=["index_right"], errors="ignore")

    records = []

    # Fast lookup for basin boundary in metric CRS
    basin_map = bas_m.set_index(PRIMARY_KEY)["geometry"].to_dict()

    for bid, grp in joined.groupby(PRIMARY_KEY, sort=False):
        grp = grp.copy()
        grp["ORD_STRA"] = grp["ORD_STRA"].fillna(-1)
        grp = grp.sort_values(["ORD_STRA", "line_len_m"], ascending=[False, False])
        row = grp.iloc[0]

        line = select_linestring(row.geometry)
        basin_poly = basin_map.get(bid)

        method = "centroid_fallback"
        stream_order = float(row["ORD_STRA"]) if pd.notna(row["ORD_STRA"]) else np.nan
        snap_km = np.nan

        if line is not None and basin_poly is not None and not basin_poly.is_empty:
            coords = list(line.coords)
            if len(coords) >= 2:
                p0 = Point(coords[0])
                p1 = Point(coords[-1])
                boundary = basin_poly.boundary
                d0 = boundary.distance(p0)
                d1 = boundary.distance(p1)
                cand = p0 if d0 <= d1 else p1

                if basin_poly.buffer(1.0).contains(cand):
                    method = "outlet_from_river"
                    sp = cand
                else:
                    method = "main_river_midpoint"
                    sp = line.interpolate(0.5, normalized=True)

                snap_km = float(line.distance(sp)) / 1000.0
            else:
                method = "main_river_midpoint"
                sp = line.interpolate(0.5, normalized=True)
                snap_km = float(line.distance(sp)) / 1000.0
        else:
            sp = basin_poly.representative_point() if basin_poly is not None else None
            method = "centroid_fallback"

        if sp is None or sp.is_empty:
            continue

        records.append({
            PRIMARY_KEY: bid,
            "support_stream_order": stream_order,
            "supportpoint_method": method,
            "qc_snap_dist_km_river": snap_km,
            "geometry": sp,
        })

    sp_m = gpd.GeoDataFrame(records, geometry="geometry", crs="EPSG:3035") if records else gpd.GeoDataFrame(columns=[PRIMARY_KEY, "support_stream_order", "supportpoint_method", "qc_snap_dist_km_river", "geometry"], crs="EPSG:3035")
    sp_wgs = sp_m.to_crs("EPSG:4326") if len(sp_m) else sp_m.to_crs("EPSG:4326")

    # Add centroid fallback for basins with no intersecting river segments
    done = set(sp_wgs[PRIMARY_KEY].astype("string"))
    missing = bas.loc[~bas[PRIMARY_KEY].astype("string").isin(done), [PRIMARY_KEY, "geometry"]].copy()
    if len(missing) > 0:
        miss = missing.copy()
        miss["geometry"] = miss.geometry.representative_point()
        miss["support_stream_order"] = np.nan
        miss["supportpoint_method"] = "centroid_fallback"
        miss["qc_snap_dist_km_river"] = np.nan
        sp_wgs = pd.concat([sp_wgs, miss[[PRIMARY_KEY, "support_stream_order", "supportpoint_method", "qc_snap_dist_km_river", "geometry"]]], ignore_index=True)
        sp_wgs = gpd.GeoDataFrame(sp_wgs, geometry="geometry", crs="EPSG:4326")

    return sp_wgs


def extract_monthly_netcdf_nearest(
    points_gdf: gpd.GeoDataFrame,
    basin_geom: gpd.GeoSeries,
    path: str,
    var_name: str,
    prefix: str,
) -> pd.DataFrame:
    ds = xr.open_dataset(path)
    try:
        da = ds[var_name]
        monthly = da.groupby("time.month").mean(dim="time", skipna=True)

        lat_name = "latitude" if "latitude" in monthly.coords else "lat"
        lon_name = "longitude" if "longitude" in monthly.coords else "lon"

        lat_vals = monthly[lat_name].values
        lon_vals = monthly[lon_name].values

        p_lat = points_gdf.geometry.y.to_numpy(dtype=float)
        p_lon_raw = points_gdf.geometry.x.to_numpy(dtype=float)
        p_lon = normalize_lon_to_grid(p_lon_raw, lon_vals)

        # Handle descending coordinates robustly
        lat_asc = np.all(np.diff(lat_vals) >= 0)
        lon_asc = np.all(np.diff(lon_vals) >= 0)

        lat_for_search = lat_vals if lat_asc else lat_vals[::-1]
        lon_for_search = lon_vals if lon_asc else lon_vals[::-1]

        ilat = nearest_index(lat_for_search, p_lat)
        ilon = nearest_index(lon_for_search, p_lon)

        if not lat_asc:
            ilat = (len(lat_vals) - 1) - ilat
        if not lon_asc:
            ilon = (len(lon_vals) - 1) - ilon

        vals = monthly.values  # month x lat x lon
        mvals = vals[:, ilat, ilon].T  # n_points x 12

        # Nearest cell coordinates + QC
        near_lat = lat_vals[ilat]
        near_lon = lon_vals[ilon]

        nearest_km = haversine_km(p_lat, p_lon, near_lat, near_lon)

        # Pure shapely pairwise point-in-basin check (avoid GeoSeries/GeometryArray binary-op issues)
        nearest_points = [Point(float(x), float(y)) for x, y in zip(near_lon, near_lat)]
        basin_vals = list(basin_geom) if hasattr(basin_geom, "__iter__") else [basin_geom] * len(nearest_points)
        if len(basin_vals) < len(nearest_points):
            basin_vals = basin_vals + [None] * (len(nearest_points) - len(basin_vals))

        in_basin = pd.Series(
            [
                bool(pt.within(poly))
                if (poly is not None and not getattr(poly, "is_empty", True))
                else False
                for pt, poly in zip(nearest_points, basin_vals)
            ],
            index=points_gdf.index
        )

        # Qualitative match label for diagnostics
        quality = pd.Series(pd.cut(
            nearest_km,
            bins=[-np.inf, 5, 25, np.inf],
            labels=["high", "medium", "low"]
        )).astype("string")

        out = pd.DataFrame({PRIMARY_KEY: points_gdf[PRIMARY_KEY].values})
        for m in range(1, 13):
            out[f"{prefix}_s{m:02d}"] = mvals[:, m - 1]

        # QC/provenance (not canonical ML predictors)
        out[f"qc_nearest_km_{prefix}"] = nearest_km
        out[f"qc_in_basin_{prefix}"] = in_basin.values
        out[f"qc_n_cells_used_{prefix}"] = 1
        out[f"qc_agg_method_{prefix}"] = "nearest_cell_supportpoint"
        out[f"qc_match_quality_{prefix}"] = quality.values

    finally:
        ds.close()

    return out


def compute_dist_to_wwtp_km(points_gdf: gpd.GeoDataFrame) -> pd.DataFrame:
    hw = pd.read_csv(HW_CSV, encoding="latin1")
    cols = [c for c in ["LAT_WWTP", "LON_WWTP"] if c in hw.columns]
    if len(cols) < 2:
        return pd.DataFrame({PRIMARY_KEY: points_gdf[PRIMARY_KEY].values, "dist_to_wwtp_km": np.nan})

    hw = hw[["LAT_WWTP", "LON_WWTP"]].dropna().copy()
    if hw.empty:
        return pd.DataFrame({PRIMARY_KEY: points_gdf[PRIMARY_KEY].values, "dist_to_wwtp_km": np.nan})

    p_rad = np.deg2rad(np.c_[points_gdf.geometry.y.values, points_gdf.geometry.x.values])
    w_rad = np.deg2rad(np.c_[hw["LAT_WWTP"].values, hw["LON_WWTP"].values])

    tree = BallTree(w_rad, metric="haversine")
    dist_rad, _ = tree.query(p_rad, k=1)
    return pd.DataFrame({
        PRIMARY_KEY: points_gdf[PRIMARY_KEY].values,
        "dist_to_wwtp_km": dist_rad[:, 0] * 6371.0088,
    })


def choose_canonical_predictor_columns(basin_df: pd.DataFrame) -> list[str]:
    """
    Canonical transferable predictors exclude QC/provenance and metadata.
    """
    cols = [c for c in basin_df.columns if is_model_predictor_column(c)]

    # Keep numeric transferable environmental predictors only for model-ready overlap.
    numeric = [c for c in cols if pd.api.types.is_numeric_dtype(basin_df[c])]
    return numeric


def build_model_ready_overlap(
    station_canonical: pd.DataFrame,
    basin_canonical: pd.DataFrame,
    station_id_cols: Iterable[str],
    basin_id_cols: Iterable[str],
) -> tuple[pd.DataFrame, pd.DataFrame, list[str]]:
    s = station_canonical.copy()
    b = basin_canonical.copy()

    cand_s = choose_canonical_predictor_columns(s)
    cand_b = choose_canonical_predictor_columns(b)

    shared = sorted(set(cand_s).intersection(cand_b))

    station_out = s[[c for c in station_id_cols if c in s.columns] + shared].copy()
    basin_out = b[[c for c in basin_id_cols if c in b.columns] + shared].copy()
    return station_out, basin_out, shared


# =====================================================
# MAIN PIPELINE
# =====================================================
print("\n=== 1) Load core inputs ===")
obs_ctx = read_obs_station_context(OBS_FOLDER)
stations_gdf = read_stations()
hydrobasins = read_hydrobasins_tiles()
atlas = read_basinatlas()
print(f"Stations loaded: {len(stations_gdf):,}")
print(f"HydroBASINS loaded: {len(hydrobasins):,}")
print(f"BasinATLAS loaded: {len(atlas):,}")


print("\n=== 2) Basin backbone + key alignment QC ===")
basin = atlas.copy()

# Attach continent tile from HydroBASINS for Europe/global split
basin = basin.merge(
    hydrobasins[[PRIMARY_KEY, "continent_tile"]],
    on=PRIMARY_KEY,
    how="left"
)

# Keep HYBAS_ID as mapping field; do not drop non-aligned rows
basin["qc_primary_vs_hybasid_mismatch_basin"] = (
    basin[PRIMARY_KEY].notna() & basin[SECONDARY_KEY].notna() & (basin[PRIMARY_KEY] != basin[SECONDARY_KEY])
)


print("\n=== 3) Station→basin assignment (primary key = hydrobasin_level12) ===")
station_map = assign_stations_to_basins(stations_gdf, hydrobasins, obs_ctx)
print(f"Stations mapped: {len(station_map):,}")


print("\n=== 4) Canonical basin supportpoints (outlet/main-river/centroid fallback) ===")
river = read_riveratlas()
support = derive_basin_supportpoints(
    basin_gdf=basin[[PRIMARY_KEY, SECONDARY_KEY, "geometry"]],
    river_gdf=river
)
print(f"Supportpoints generated: {len(support):,}")


print("\n=== 5) Basin-context predictors at supportpoint ===")
# stream_order and supportpoint method already in support
ctx_dist = compute_dist_to_wwtp_km(support)

# Basin geometry lookup for in-basin QC checks in netCDF sampling
basin_geom_lookup = basin.set_index(PRIMARY_KEY).geometry
basin_geom_for_support = support[PRIMARY_KEY].map(basin_geom_lookup)


df_dis = extract_monthly_netcdf_nearest(
    points_gdf=support[[PRIMARY_KEY, "geometry"]],
    basin_geom=basin_geom_for_support,
    path=PATH_DISCHARGE,
    var_name="discharge",
    prefix="discharge"
)

df_wt = extract_monthly_netcdf_nearest(
    points_gdf=support[[PRIMARY_KEY, "geometry"]],
    basin_geom=basin_geom_for_support,
    path=PATH_WATERTEMP,
    var_name="waterTemperature",
    prefix="watertemp"
)


print("\n=== 6) Build canonical basin table ===")
# Merge supportpoint context + monthly netcdf onto basin atlas backbone
basin_canonical = (
    basin.merge(support.drop(columns="geometry", errors="ignore"), on=PRIMARY_KEY, how="left")
         .merge(ctx_dist, on=PRIMARY_KEY, how="left")
         .merge(df_dis, on=PRIMARY_KEY, how="left")
         .merge(df_wt, on=PRIMARY_KEY, how="left")
)

# Explicit QC/provenance split fields already prefixed qc_
basin_canonical = sanitize_columns(basin_canonical)


print("\n=== 7) Build canonical station table (inherit basin-canonical predictors) ===")
station_id_cols = [
    "wqms_id", "wqms_lat", "wqms_lon", "country_name",
    PRIMARY_KEY, SECONDARY_KEY,
    f"{PRIMARY_KEY}_obs", f"{PRIMARY_KEY}_spatial", f"{SECONDARY_KEY}_spatial",
    "continent_tile",
    "qc_has_obs_key", "qc_has_spatial_key", "qc_obs_vs_spatial_key_mismatch", "qc_primary_vs_hybasid_mismatch"
]
station_id_cols = [c for c in station_id_cols if c in station_map.columns]

# Bring basin features to stations by canonical primary key
station_canonical = station_map.merge(
    basin_canonical.drop(columns=[SECONDARY_KEY], errors="ignore"),
    on=PRIMARY_KEY,
    how="left",
    suffixes=("", "_basin")
)

# Keep station HYBAS_ID from station map (mapping/QC field), and optional basin HYBAS_ID as extra QC
if f"{SECONDARY_KEY}_basin" in station_canonical.columns:
    station_canonical["qc_hybasid_from_basin"] = station_canonical[f"{SECONDARY_KEY}_basin"]

station_canonical = sanitize_columns(station_canonical)


print("\n=== 8) Europe subsets ===")
station_canonical["is_europe_station"] = station_canonical.get("country_name", pd.Series(index=station_canonical.index)).isin(EUROPE_COUNTRIES)
basin_canonical["is_europe_basin"] = basin_canonical.get("continent_tile", pd.Series(index=basin_canonical.index)).eq("Europe")

station_global = station_canonical.copy()
station_europe = station_canonical.loc[station_canonical["is_europe_station"]].copy()

basin_global = basin_canonical.copy()
basin_europe = basin_canonical.loc[basin_canonical["is_europe_basin"]].copy()


print("\n=== 9) Model-ready overlap (exact shared transferable predictors) ===")
station_model_global, basin_model_global, shared_global = build_model_ready_overlap(
    station_canonical=station_global,
    basin_canonical=basin_global,
    station_id_cols=["wqms_id", PRIMARY_KEY, SECONDARY_KEY],
    basin_id_cols=[PRIMARY_KEY, SECONDARY_KEY],
)
station_model_europe, basin_model_europe, shared_eu = build_model_ready_overlap(
    station_canonical=station_europe,
    basin_canonical=basin_europe,
    station_id_cols=["wqms_id", PRIMARY_KEY, SECONDARY_KEY],
    basin_id_cols=[PRIMARY_KEY, SECONDARY_KEY],
)


print("\n=== 10) QC tables ===")
# Station QC
station_qc_cols = [
    "wqms_id", "country_name", PRIMARY_KEY, SECONDARY_KEY,
    f"{PRIMARY_KEY}_obs", f"{PRIMARY_KEY}_spatial", f"{SECONDARY_KEY}_spatial",
    "qc_has_obs_key", "qc_has_spatial_key", "qc_obs_vs_spatial_key_mismatch", "qc_primary_vs_hybasid_mismatch",
]
station_qc_cols = [c for c in station_qc_cols if c in station_global.columns]
station_qc_global = station_global[station_qc_cols].copy()
station_qc_europe = station_europe[station_qc_cols].copy()

# Basin QC
basin_qc_cols = [c for c in basin_global.columns if c in {
    PRIMARY_KEY, SECONDARY_KEY, "continent_tile", "supportpoint_method", "support_stream_order",
    "qc_snap_dist_km_river", "qc_primary_vs_hybasid_mismatch_basin",
    "qc_nearest_km_discharge", "qc_in_basin_discharge", "qc_n_cells_used_discharge", "qc_agg_method_discharge", "qc_match_quality_discharge",
    "qc_nearest_km_watertemp", "qc_in_basin_watertemp", "qc_n_cells_used_watertemp", "qc_agg_method_watertemp", "qc_match_quality_watertemp",
}]
basin_qc_global = basin_global[basin_qc_cols].copy()
basin_qc_europe = basin_europe[basin_qc_cols].copy()


print("\n=== 11) Save outputs ===")
os.makedirs(OUT_DIR, exist_ok=True)

paths = {
    # canonical tables
    "station_global": f"{OUT_DIR}/features_canonical_station_global.csv",
    "station_europe": f"{OUT_DIR}/features_canonical_station_europe.csv",
    "basin_global": f"{OUT_DIR}/features_canonical_basin_global.csv",
    "basin_europe": f"{OUT_DIR}/features_canonical_basin_europe.csv",

    # model-ready overlap tables (exact transferable overlap)
    "station_model_global": f"{OUT_DIR}/features_modelready_station_global.csv",
    "station_model_europe": f"{OUT_DIR}/features_modelready_station_europe.csv",
    "basin_model_global": f"{OUT_DIR}/features_modelready_basin_global.csv",
    "basin_model_europe": f"{OUT_DIR}/features_modelready_basin_europe.csv",

    # QC tables
    "station_qc_global": f"{OUT_DIR}/features_qc_station_global.csv",
    "station_qc_europe": f"{OUT_DIR}/features_qc_station_europe.csv",
    "basin_qc_global": f"{OUT_DIR}/features_qc_basin_global.csv",
    "basin_qc_europe": f"{OUT_DIR}/features_qc_basin_europe.csv",

    # overlap feature lists
    "shared_global": f"{OUT_DIR}/features_modelready_shared_columns_global.csv",
    "shared_europe": f"{OUT_DIR}/features_modelready_shared_columns_europe.csv",
}

station_global.to_csv(paths["station_global"], index=False)
station_europe.to_csv(paths["station_europe"], index=False)
basin_global.to_csv(paths["basin_global"], index=False)
basin_europe.to_csv(paths["basin_europe"], index=False)

station_model_global.to_csv(paths["station_model_global"], index=False)
station_model_europe.to_csv(paths["station_model_europe"], index=False)
basin_model_global.to_csv(paths["basin_model_global"], index=False)
basin_model_europe.to_csv(paths["basin_model_europe"], index=False)

station_qc_global.to_csv(paths["station_qc_global"], index=False)
station_qc_europe.to_csv(paths["station_qc_europe"], index=False)
basin_qc_global.to_csv(paths["basin_qc_global"], index=False)
basin_qc_europe.to_csv(paths["basin_qc_europe"], index=False)

pd.DataFrame({"feature": shared_global}).to_csv(paths["shared_global"], index=False)
pd.DataFrame({"feature": shared_eu}).to_csv(paths["shared_europe"], index=False)


print("\n=== DONE ===")
print(f"Saved global canonical station rows: {len(station_global):,}")
print(f"Saved global canonical basin rows:   {len(basin_global):,}")
print(f"Saved europe canonical station rows: {len(station_europe):,}")
print(f"Saved europe canonical basin rows:   {len(basin_europe):,}")
print(f"Shared model-ready features (global): {len(shared_global)}")
print(f"Shared model-ready features (europe): {len(shared_eu)}")
for k, v in paths.items():
    print(f"- {k}: {v}")