# -*- coding: utf-8 -*-
"""2_median_observations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HCUURNkqtGYjMuTNmW4vEZ_DnG2n4S01
"""

# -*- coding: utf-8 -*-
"""2_median_observations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DjYLSS-i2wrDVWNMubobfPTlboafWTlG
"""

from google.colab import drive
drive.mount('/content/drive')
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import geopandas as gpd
import matplotlib.pyplot as plt
import pandas as pd
from shapely.geometry import Point
from functools import lru_cache
from collections import Counter

# =====================================================================
# OBSERVATION PIPELINE → SITE-MONTH CLIMATOLOGY (voor ML)
# =====================================================================

import os
import pandas as pd
from shapely.geometry import Point
import geopandas as gpd

# -------------------------------------------------
# Config
# -------------------------------------------------
OBS_FOLDER = '/content/drive/MyDrive/SamuelRebel_thesis/T2/data/wq_data/wqms-csv/'
SITE_INFO  = '/content/drive/MyDrive/SamuelRebel_thesis/T2/data/wq_data/wqms_site_info.csv'
OUT_DIR    = "/content/drive/MyDrive/SamuelRebel_thesis/T2/T3/output/observations/mean_test"

YEAR_START, YEAR_END_EXCL = 2010, 2024  # [2010, 2024)
APPLY_LANDMASK   = False     # zet True als je landmask (Natural Earth) wilt toepassen

# climatology: 1 rij per (wqms_id, month) met mediane obs over alle jaren
APPLY_CLIMATOLOGY = True

# Flag-based outliers
FLAG_COL = "flag"
OUTLIER_FLAG_VALUE = "*"
DROP_FLAG_OUTLIERS = True  # zet False als je dit tijdelijk uit wil zetten

# Balancing (wereldwijde scheefheid)
APPLY_BALANCING_TOP3 = True
COUNTRY_COL = "country_name"
RANDOM_STATE = 42
BALANCING_REPORT_SUMMARY = "balancing_report_summary.csv"
BALANCING_REPORT_BY_COUNTRY = "balancing_report_by_country.csv"

# Kolommen droppen bij export
DROP_COLS = ["geometry", "flag", "detection_limit", "imputation_method"]

# -------------------------------------------------
# Helpers
# -------------------------------------------------
def load_obs_files(obs_folder: str) -> dict:
    files = [f for f in os.listdir(obs_folder) if f.endswith('.csv')]
    data = {}
    for f in files:
        df = pd.read_csv(os.path.join(obs_folder, f))
        data[f] = df
    return data

def left_join_site_info(d: dict, site_info_path: str) -> dict:
    site_info_df = pd.read_csv(site_info_path)
    out = {}
    for name, df in d.items():
        out[name] = df.merge(site_info_df, on='wqms_id', how='left')
    return out

def remove_flagged_outliers_df(
    df: pd.DataFrame,
    flag_col: str = "flag",
    outlier_flag_value: str = "*"
) -> pd.DataFrame:
    """
    Verwijder alleen rijen waar flag == '*'.
    Houd rijen met missende flag (NaN/<NA>) expliciet vast.
    """
    if flag_col not in df.columns:
        return df.copy()

    flags = df[flag_col].astype("string")

    # KEEP als: flag is missing OR flag != '*'
    keep = flags.isna() | (flags != outlier_flag_value)

    return df.loc[keep].copy()

def balance_by_top3_countries_df(
    df: pd.DataFrame,
    country_col: str = "country_name",
    random_state: int = 42,
    shuffle: bool = True
) -> pd.DataFrame:
    """
    Downsample top-3 landen naar n = count(3e land).
    Niet-top3 landen blijven volledig behouden.
    """
    if country_col not in df.columns:
        raise ValueError(f"Kolom '{country_col}' ontbreekt in df.")

    counts = df[country_col].value_counts(dropna=False)
    if len(counts) < 3:
        return df.copy()

    top3 = counts.index[:3]
    n_third = int(counts.iloc[2])

    parts = []
    parts.append(df.loc[~df[country_col].isin(top3)])

    for country in top3:
        subset = df.loc[df[country_col] == country]
        if len(subset) <= n_third:
            parts.append(subset)
        else:
            parts.append(subset.sample(n=n_third, random_state=random_state))

    balanced = pd.concat(parts, ignore_index=True)
    if shuffle:
        balanced = balanced.sample(frac=1, random_state=random_state).reset_index(drop=True)
    return balanced

def _country_label(val) -> str:
    if pd.isna(val):
        return "<NA>"
    return str(val)

def build_balancing_report(before_df: pd.DataFrame, after_df: pd.DataFrame, file_name: str, country_col: str):
    """
    Return:
      summary_row: 1 dict per file
      country_rows: meerdere dicts per file/country met before/after counts
    """
    if country_col not in before_df.columns:
        return (
            {
                "file_name": file_name,
                "country_col": country_col,
                "balancing_applied": False,
                "reason": "country_col_missing",
                "rows_before": int(len(before_df)),
                "rows_after": int(len(after_df)),
                "countries_before": 0,
                "countries_after": 0,
                "top3_before": "",
                "target_n_third_before": np.nan,
            },
            []
        )

    before_counts = before_df[country_col].value_counts(dropna=False)
    after_counts = after_df[country_col].value_counts(dropna=False)

    top3_vals = before_counts.index[:3].tolist()
    top3_str = "|".join(_country_label(v) for v in top3_vals)
    n_third = int(before_counts.iloc[2]) if len(before_counts) >= 3 else np.nan

    reason = "balanced" if len(before_counts) >= 3 else "lt_3_countries"
    summary_row = {
        "file_name": file_name,
        "country_col": country_col,
        "balancing_applied": len(before_counts) >= 3,
        "reason": reason,
        "rows_before": int(len(before_df)),
        "rows_after": int(len(after_df)),
        "countries_before": int(before_counts.shape[0]),
        "countries_after": int(after_counts.shape[0]),
        "top3_before": top3_str,
        "target_n_third_before": n_third,
    }

    union_countries = set(before_counts.index.tolist()) | set(after_counts.index.tolist())
    country_rows = []
    for c in sorted(union_countries, key=lambda x: _country_label(x)):
        b = int(before_counts.get(c, 0))
        a = int(after_counts.get(c, 0))
        country_rows.append({
            "file_name": file_name,
            "country_name": _country_label(c),
            "count_before": b,
            "count_after": a,
            "delta_after_minus_before": a - b,
            "downsampled": a < b,
            "upsampled": a > b,
        })

    return summary_row, country_rows

def ensure_geometry(
    df: pd.DataFrame,
    lat_col: str = "wqms_lat",
    lon_col: str = "wqms_lon",
    crs: str = "EPSG:4326",
    auto_swap: bool = False
) -> gpd.GeoDataFrame:
    if isinstance(df, gpd.GeoDataFrame) and "geometry" in df.columns and df.geometry.notna().any():
        gdf = df.copy()
        if gdf.crs is None:
            gdf.set_crs(crs, inplace=True)
        return gdf

    if lat_col not in df.columns or lon_col not in df.columns:
        candidates = [("lat", "lon"), ("latitude", "longitude")]
        for la, lo in candidates:
            if la in df.columns and lo in df.columns:
                lat_col, lon_col = la, lo
                break
        else:
            raise ValueError(f"Geen lat/lon-kolommen gevonden (gezocht: '{lat_col}', '{lon_col}').")

    lat = pd.to_numeric(df[lat_col], errors="coerce")
    lon = pd.to_numeric(df[lon_col], errors="coerce")

    if auto_swap:
        frac_lat_out = (lat.abs() > 90).mean()
        frac_lon_in  = (lon.abs() <= 90).mean()
        if frac_lat_out > 0.5 and frac_lon_in > 0.5:
            lat, lon = lon, lat

    mask_valid = lat.between(-90, 90) & lon.between(-180, 180)
    df2 = df.loc[mask_valid].copy()
    df2["geometry"] = [Point(xy) for xy in zip(lon.loc[mask_valid], lat.loc[mask_valid])]
    return gpd.GeoDataFrame(df2, geometry="geometry", crs=crs)

def apply_year_filter(
    df: pd.DataFrame,
    col: str = "dates",
    start_year: int = 2010,
    end_year_excl: int = 2024
) -> pd.DataFrame:
    if col not in df.columns:
        raise ValueError(f"Kolom '{col}' ontbreekt.")
    out = df.copy()
    out[col] = pd.to_datetime(out[col], errors="coerce", utc=True).dt.tz_convert(None)
    mask = (out[col].dt.year >= start_year) & (out[col].dt.year < end_year_excl)
    return out.loc[mask].copy()

def add_calendar_cols(df: pd.DataFrame, date_col: str = "dates") -> pd.DataFrame:
    out = df.copy()
    out[date_col] = pd.to_datetime(out[date_col], errors="coerce")
    out["year"] = out[date_col].dt.year
    out["month"] = out[date_col].dt.month
    out["year_month"] = out[date_col].dt.to_period("M").astype(str)
    return out

def landmask_natural_earth(gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    """Optioneel: filter punten op land met Natural Earth 'land' 110m (vereist cartopy/shapely)."""
    try:
        import cartopy.feature as cfeature
        from shapely.ops import unary_union
    except Exception as e:
        raise ImportError("Voor landmask heb je 'cartopy' en 'shapely' nodig.") from e

    land_feat = cfeature.NaturalEarthFeature("physical", "land", "110m")
    land_geom = unary_union(list(land_feat.geometries()))

    pts = gdf.to_crs(epsg=4326).copy()
    mask = pts.geometry.apply(
        lambda geom: geom.is_valid and geom.within(land_geom) if geom is not None else False
    )
    return pts.loc[mask].copy()

# -------------------------------------------------
# Climatology aggregatie (median) met behoud schema
# -------------------------------------------------
def aggregate_to_site_month_median_preserve_schema(df: pd.DataFrame) -> pd.DataFrame:
    """
    1 rij per (wqms_id, month) met mediane 'obs' over alle jaren,
    met behoud van dezelfde kolommen als input.

    - 'obs' := median(obs) (na numeric coercion)
    - 'year', 'year_month', 'dates' van het LAATSTE jaar in de groep
    - overige kolommen via 'first'
    """
    required = {"wqms_id", "month", "year", "obs", "dates"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Ontbrekende kolommen voor aggregatie: {missing}")

    df = df.copy()
    df["dates"] = pd.to_datetime(df["dates"], errors="coerce")

    # zorg dat obs numeriek is voor median
    df["obs"] = pd.to_numeric(df["obs"], errors="coerce")

    med = (
        df.groupby(["wqms_id", "month"])["obs"]
          .median()
          .rename("obs_median")
    )

    idx_max_year = (
        df.sort_values(["wqms_id", "month", "year"], ascending=[True, True, True])
          .groupby(["wqms_id", "month"], as_index=False)
          .tail(1)
          .set_index(["wqms_id", "month"])
    )

    firsts = (
        df.sort_values(["wqms_id", "month"])
          .groupby(["wqms_id", "month"], as_index=False)
          .first()
          .set_index(["wqms_id", "month"])
    )

    out = firsts.join(med, how="left")
    out["obs"] = out["obs_median"]
    out = out.drop(columns=["obs_median"], errors="ignore")

    for col in ["year", "dates", "year_month"]:
        if col in out.columns and col in idx_max_year.columns:
            out[col] = idx_max_year[col]

    if "dates" in out.columns:
        out["dates"] = pd.to_datetime(out["dates"], errors="coerce")
        if "year" in out.columns:
            out["year"] = out["dates"].dt.year
        if "year_month" in out.columns:
            out["year_month"] = out["dates"].dt.to_period("M").astype(str)

    out = out.reset_index()
    out["obs"] = pd.to_numeric(out["obs"], errors="coerce")
    return out

# -------------------------------------------------
# Pipeline
# -------------------------------------------------
os.makedirs(OUT_DIR, exist_ok=True)

# 1) Laden + join site_info
obs_data    = load_obs_files(OBS_FOLDER)
merged_data = left_join_site_info(obs_data, SITE_INFO)

# 1b) Flagged outliers verwijderen (flag == "*")
if DROP_FLAG_OUTLIERS:
    merged_data = {
        name: remove_flagged_outliers_df(df, flag_col=FLAG_COL, outlier_flag_value=OUTLIER_FLAG_VALUE)
        for name, df in merged_data.items()
    }

# 2) (VERWIJDERD) z-score outlier removal per station


# 4) (VERWIJDERD) percentiel-filter / negatieve waarden filter

# 5) Geometry toevoegen
with_geom = {
    name: ensure_geometry(df, lat_col="wqms_lat", lon_col="wqms_lon", auto_swap=True)
    for name, df in merged_data.items()
}

# 6) Jaarfilter [2010, 2024)
recent_data = {
    name: apply_year_filter(gdf, col="dates", start_year=YEAR_START, end_year_excl=YEAR_END_EXCL)
    for name, gdf in with_geom.items()
}

# 7) Optioneel landmask
if APPLY_LANDMASK:
    onland_data = {name: landmask_natural_earth(gdf) for name, gdf in recent_data.items()}
else:
    onland_data = recent_data

# 8) Kalenderkolommen
monthly_data = {name: add_calendar_cols(gdf, "dates") for name, gdf in onland_data.items()}

# 8b) Climatology: median per (wqms_id, month)
if APPLY_CLIMATOLOGY:
    aggregated_monthly = {}
    for name, gdf in monthly_data.items():
        df_plain = pd.DataFrame(gdf.drop(columns="geometry"))
        agg_df = aggregate_to_site_month_median_preserve_schema(df_plain)
        aggregated_monthly[name] = agg_df
    monthly_data = aggregated_monthly


# pas daarna eventueel balancing
balancing_summary_rows = []
balancing_country_rows = []
if APPLY_BALANCING_TOP3:
    balanced_monthly = {}
    for name, df in monthly_data.items():
        before_df = pd.DataFrame(df).copy()
        after_df = balance_by_top3_countries_df(before_df, country_col=COUNTRY_COL, random_state=RANDOM_STATE)
        balanced_monthly[name] = after_df

        summary_row, country_rows = build_balancing_report(
            before_df=before_df,
            after_df=after_df,
            file_name=name,
            country_col=COUNTRY_COL
        )
        balancing_summary_rows.append(summary_row)
        balancing_country_rows.extend(country_rows)
    monthly_data = balanced_monthly
else:
    # Ook zonder balancing toch transparante rapportage schrijven
    for name, df in monthly_data.items():
        before_df = pd.DataFrame(df).copy()
        summary_row, country_rows = build_balancing_report(
            before_df=before_df,
            after_df=before_df,
            file_name=name,
            country_col=COUNTRY_COL
        )
        summary_row["balancing_applied"] = False
        summary_row["reason"] = "balancing_disabled"
        balancing_summary_rows.append(summary_row)
        balancing_country_rows.extend(country_rows)


# 9) Export (drop columns indien aanwezig)
for name, df_like in monthly_data.items():
    df_out = (
        pd.DataFrame(df_like)
        .drop(columns=[c for c in DROP_COLS if c in pd.DataFrame(df_like).columns], errors="ignore")
        .copy()
    )
    out_path = os.path.join(OUT_DIR, name)
    df_out.to_csv(out_path, index=False)

# 10) Balancing report export
if balancing_summary_rows:
    pd.DataFrame(balancing_summary_rows).to_csv(
        os.path.join(OUT_DIR, BALANCING_REPORT_SUMMARY), index=False
    )
if balancing_country_rows:
    pd.DataFrame(balancing_country_rows).to_csv(
        os.path.join(OUT_DIR, BALANCING_REPORT_BY_COUNTRY), index=False
    )