# -*- coding: utf-8 -*-
"""3_modeltrain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dqwSTwyXFOMY572VyaG9IRI8rzFzaZdK
"""

# -*- coding: utf-8 -*-
"""3_modeltrain (updated for canonical/modelready pipeline)

Belangrijkste updates:
- Mode-volgorde expliciet: eerst EU_train_NL_test, daarna WORLD_all
- Aansluiting op script 1/2 modelready outputs (hydrobasin_level12-key)
- Pollutant-file selectie sluit balancing-report CSV's uit
- Incrementele opslag per pollutant (all_results + feature_importance)
- FI-summary wordt tussentijds ververst zodat crash niet alles kost
"""

from google.colab import drive
drive.mount('/content/drive')

import glob
import os
import re
import tempfile
from typing import Iterable

import numpy as np
import pandas as pd

import cudf
from cuml.ensemble import RandomForestRegressor as cuRF

from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import GroupKFold, KFold
from sklearn.inspection import permutation_importance


try:
    from cuml.internals.memory_utils import set_global_output_type
except Exception:
    set_global_output_type = None

# =====================================================
# FEATURE FILTERING + READABLE LABELS
# =====================================================
NON_PREDICTOR_EXACT = {
    "HYBAS_ID", "hydrobasin_level12", "geometry",
    "NEXT_DOWN", "NEXT_SINK", "MAIN_BAS", "PFAF_ID", "SORT", "ORDER",
    "DIST_SINK", "DIST_MAIN", "SUB_AREA", "UP_AREA", "ENDO", "COAST",
    "supportpoint_method", "support_stream_order", "continent_tile",
    "country_name", "country_name_obs", "wqms_id", "wqms_lat", "wqms_lon",
    "hydrobasin_level12_obs", "hydrobasin_level12_spatial", "HYBAS_ID_spatial",
    "qc_has_obs_key", "qc_has_spatial_key", "qc_obs_vs_spatial_key_mismatch",
    "qc_primary_vs_hybasid_mismatch", "qc_primary_vs_hybasid_mismatch_basin",
    "qc_hybasid_from_basin", "gad_id_smj",
}

NON_PREDICTOR_CLASS_CODES = {
    "clz_cl_smj", "cls_cl_smj", "glc_cl_smj", "pnv_cl_smj", "wet_cl_smj",
    "tbi_cl_smj", "tec_cl_smj", "fmh_cl_smj", "fec_cl_smj", "lit_cl_smj",
}

NON_PREDICTOR_PREFIXES = ("qc_", "prov_")


def is_model_predictor_column(column: str) -> bool:
    c = str(column).strip()
    if c in NON_PREDICTOR_EXACT or c in NON_PREDICTOR_CLASS_CODES:
        return False
    if c.startswith(NON_PREDICTOR_PREFIXES):
        return False
    if c.endswith("_id") or "_id_" in c.lower():
        return False
    if re.search(r"_cl_", c):
        return False
    return True


BASE_LABELS = {
    "dis_m3": "Natural river discharge",
    "run_mm": "Runoff depth",
    "inu_pc": "Inundated area",
    "lka_pc": "Lake area",
    "lkv_mc": "Lake volume",
    "rev_mc": "Reservoir volume",
    "dor_pc": "Degree of river regulation",
    "ria_ha": "River area",
    "riv_tc": "River volume",
    "gwt_cm": "Groundwater table depth",
    "ele_mt": "Elevation",
    "slp_dg": "Terrain slope",
    "sgr_dk": "Stream gradient",
    "tmp_dc": "Air temperature",
    "pre_mm": "Precipitation",
    "pet_mm": "Potential evapotranspiration",
    "aet_mm": "Actual evapotranspiration",
    "ari_ix": "Aridity index",
    "cmi_ix": "Climate moisture index",
    "snw_pc": "Snow cover",
    "glc_pc": "Land-cover fraction",
    "pnv_pc": "Potential natural vegetation fraction",
    "wet_pc": "Wetland fraction",
    "for_pc": "Forest cover",
    "crp_pc": "Cropland cover",
    "pst_pc": "Pasture cover",
    "ire_pc": "Irrigated area",
    "gla_pc": "Glacier cover",
    "prm_pc": "Permafrost extent",
    "pac_pc": "Protected area coverage",
    "cly_pc": "Soil clay fraction",
    "slt_pc": "Soil silt fraction",
    "snd_pc": "Soil sand fraction",
    "soc_th": "Soil organic carbon",
    "swc_pc": "Soil water content",
    "kar_pc": "Karst area",
    "ero_kh": "Soil erosion",
    "pop_ct": "Population count",
    "ppd_pk": "Population density",
    "urb_pc": "Urban area",
    "nli_ix": "Night-time lights index",
    "rdd_mk": "Road density",
    "hft_ix": "Human footprint index",
    "gdp_ud": "Gross domestic product",
    "hdi_ix": "Human Development Index",
    "dist_to_wwtp_km": "Distance to nearest wastewater treatment plant",
    "discharge": "Monthly discharge at basin support point",
    "watertemp": "Monthly water temperature at basin support point",
}

UNITS = {
    "dis_m3": "m3/s", "run_mm": "mm/yr", "inu_pc": "%", "lka_pc": "%",
    "lkv_mc": "million m3", "rev_mc": "million m3", "dor_pc": "%",
    "ria_ha": "ha", "gwt_cm": "cm", "ele_mt": "m", "slp_dg": "degrees",
    "tmp_dc": "0.1 deg C", "pre_mm": "mm", "pet_mm": "mm", "aet_mm": "mm",
    "snw_pc": "%", "glc_pc": "%", "pnv_pc": "%", "wet_pc": "%",
    "for_pc": "%", "crp_pc": "%", "pst_pc": "%", "ire_pc": "%",
    "gla_pc": "%", "prm_pc": "%", "pac_pc": "%", "cly_pc": "%",
    "slt_pc": "%", "snd_pc": "%", "swc_pc": "%", "urb_pc": "%",
    "ppd_pk": "people/km2", "dist_to_wwtp_km": "km",
}

SUFFIX_LABELS = {
    "syr": "annual value in sub-basin",
    "uyr": "annual value for upstream catchment",
    "sav": "average in sub-basin",
    "uav": "average for upstream catchment",
    "smn": "minimum in sub-basin",
    "umn": "minimum for upstream catchment",
    "smx": "maximum in sub-basin",
    "umx": "maximum for upstream catchment",
    "slt": "long-term low value in sub-basin",
    "ult": "long-term low value for upstream catchment",
    "sse": "share in sub-basin",
    "use": "share for upstream catchment",
    "ssu": "sum in sub-basin",
    "usu": "sum for upstream catchment",
    "pyr": "annual average",
    "pmn": "minimum monthly average",
    "pmx": "maximum monthly average",
    "pva": "variability indicator",
    "sg1": "class 1 in sub-basin",
    "ug1": "class 1 for upstream catchment",
    "sg2": "class 2 in sub-basin",
    "ug2": "class 2 for upstream catchment",
}

LAND_COVER_CLASSES = {
    **{f"s{i:02d}": f"class {i:02d} in sub-basin" for i in range(1, 23)},
    **{f"u{i:02d}": f"class {i:02d} for upstream catchment" for i in range(1, 23)},
}
MONTH_SUFFIXES = {f"s{i:02d}": f"month {i:02d} in sub-basin" for i in range(1, 13)}
MONTH_SUFFIXES.update({f"u{i:02d}": f"month {i:02d} for upstream catchment" for i in range(1, 13)})


def split_hydroatlas_code(feature: str) -> tuple[str, str | None]:
    f = str(feature)
    for suffix in sorted(set(SUFFIX_LABELS) | set(LAND_COVER_CLASSES) | set(MONTH_SUFFIXES), key=len, reverse=True):
        token = "_" + suffix
        if f.endswith(token):
            return f[: -len(token)], suffix
    return f, None


def feature_label(feature: str, include_code: bool = True) -> str:
    raw = str(feature)
    base, suffix = split_hydroatlas_code(raw)
    base_label = BASE_LABELS.get(base, raw.replace("_", " "))

    if suffix is None:
        label = base_label
    elif base in {"pre_mm", "pet_mm", "aet_mm", "tmp_dc", "snw_pc", "cmi_ix", "discharge", "watertemp"} and suffix in MONTH_SUFFIXES:
        label = f"{base_label}, {MONTH_SUFFIXES[suffix]}"
    elif base in {"glc_pc", "pnv_pc", "wet_pc"} and suffix in LAND_COVER_CLASSES:
        label = f"{base_label}, {LAND_COVER_CLASSES[suffix]}"
    else:
        suffix_label = SUFFIX_LABELS.get(suffix) or LAND_COVER_CLASSES.get(suffix) or MONTH_SUFFIXES.get(suffix)
        label = f"{base_label}, {suffix_label}" if suffix_label else base_label

    unit = UNITS.get(base)
    if unit:
        label = f"{label} [{unit}]"
    if include_code:
        label = f"{label} ({raw})"
    return label



# =====================================================
# CONFIG
# =====================================================
RUN_MODES = ("EU_train_NL_test", "WORLD_all")  # gewenste volgorde: EU -> WORLD

COUNTRY_FIELD = "country_name"
NL_NAME = "Netherlands"
STRICT_TRANSFER = False  # False: NL mag in train (behalve test fold), True: NL volledig uitgesloten

N_SPLITS_RANDOM = 5
N_SPLITS_STATION = 5
N_SPLITS_BASIN = 5
N_SPLITS_COUNTRY = 5
MIN_GROUP_SIZE_BASIN = 5
MIN_GROUP_SIZE_COUNTRY = 5
SEED = 42

DEBUG_FOLD_COUNTS = False

EUROPE_COUNTRIES = {
    "Albania", "Andorra", "Armenia", "Austria", "Azerbaijan", "Belarus", "Belgium",
    "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Cyprus", "Czechia", "Czech Republic",
    "Denmark", "Estonia", "Finland", "France", "Georgia", "Germany", "Greece", "Hungary",
    "Iceland", "Ireland", "Italy", "Kazakhstan", "Kosovo", "Latvia", "Liechtenstein",
    "Lithuania", "Luxembourg", "Malta", "Moldova", "Monaco", "Montenegro", "Netherlands",
    "North Macedonia", "Republic of Macedonia", "Norway", "Poland", "Portugal", "Romania",
    "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden",
    "Switzerland", "Turkey", "Ukraine", "United Kingdom", "Vatican City",
}


# =====================================================
# PREFLIGHT CHECKS
# =====================================================
def _require_paths_exist(paths: list[str], label: str):
    missing = [p for p in paths if not os.path.exists(p)]
    if missing:
        raise FileNotFoundError(f"[{label}] Ontbrekende paden: {missing}")


def _read_header_cols(csv_path: str) -> list[str]:
    return pd.read_csv(csv_path, nrows=0).columns.tolist()


def run_preflight_checks(
    pollutant_dir: str,
    features_path_europe: str,
    features_path_world: str,
    shared_features_europe: str,
    shared_features_world: str,
    output_base_eu_nl: str,
    output_base_world: str,
    output_files: str,
):
    print("\n=== PREFLIGHT CHECKS ===")

    # 1) Bestanden/mappen bestaan
    _require_paths_exist(
        [pollutant_dir, features_path_europe, features_path_world, shared_features_europe, shared_features_world],
        label="exists"
    )

    # 2) Pollutant files aanwezig
    pollutant_files = list_pollutant_files(pollutant_dir)
    if not pollutant_files:
        raise ValueError(f"Geen pollutant CSV's gevonden in: {pollutant_dir}")
    print(f"✅ Pollutant files gevonden: {len(pollutant_files)}")

    # 3) Vereiste feature-kolommen aanwezig
    req_feature_cols = {"hydrobasin_level12"}
    feat_eu_cols = set(_read_header_cols(features_path_europe))
    feat_w_cols = set(_read_header_cols(features_path_world))

    if not req_feature_cols.issubset(feat_eu_cols):
        raise ValueError(f"Europe features missen verplichte kolommen: {req_feature_cols - feat_eu_cols}")
    if not req_feature_cols.issubset(feat_w_cols):
        raise ValueError(f"World features missen verplichte kolommen: {req_feature_cols - feat_w_cols}")
    print("✅ Feature headers bevatten verplichte basin-key kolommen")

    # 4) Shared feature lists valide
    shared_eu = read_shared_feature_list(shared_features_europe)
    shared_w = read_shared_feature_list(shared_features_world)
    if not shared_eu or not shared_w:
        raise ValueError("Shared feature list is leeg of ongeldig (EU/WORLD).")

    miss_eu = [c for c in shared_eu if c not in feat_eu_cols]
    miss_w = [c for c in shared_w if c not in feat_w_cols]
    if miss_eu:
        raise ValueError(f"Europe features missen shared kolommen (eerste 10): {miss_eu[:10]}")
    if miss_w:
        raise ValueError(f"World features missen shared kolommen (eerste 10): {miss_w[:10]}")
    print(f"✅ Shared features valide (EU={len(shared_eu)}, WORLD={len(shared_w)})")

    # 5) Observatiekolommen in sample controleren (header-only)
    req_obs_cols = {"wqms_id", "obs", "month", "hydrobasin_level12"}
    sample_files = pollutant_files[: min(20, len(pollutant_files))]
    obs_bad = []
    for p in sample_files:
        cols = set(_read_header_cols(p))
        miss = req_obs_cols - cols
        if miss:
            obs_bad.append((os.path.basename(p), sorted(list(miss))))
    if obs_bad:
        raise ValueError(f"Observatiekolommen missen in sample files: {obs_bad[:5]}")
    print(f"✅ Observatieheaders ok in sample van {len(sample_files)} files")

    # 6) Outputmappen schrijfbaar
    for d in [output_base_eu_nl, output_base_world, output_files]:
        os.makedirs(d, exist_ok=True)
    print("✅ Output directories writeable")

    print("=== PREFLIGHT OK ===\n")


# =====================================================
# METRICS
# =====================================================
def safe_div(numer: float, denom: float, eps: float = 1e-12) -> float:
    if denom is None or np.isnan(denom) or abs(denom) < eps:
        return np.nan
    return float(numer) / float(denom)


def compute_rmse_and_nrmse(y_true: np.ndarray, y_pred: np.ndarray):
    rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
    y_mean = float(np.mean(y_true)) if len(y_true) else np.nan
    y_std = float(np.std(y_true, ddof=0)) if len(y_true) else np.nan
    y_range = float(np.max(y_true) - np.min(y_true)) if len(y_true) else np.nan

    return (
        rmse,
        safe_div(rmse, y_mean),
        safe_div(rmse, y_range),
        safe_div(rmse, y_std),
    )


# =====================================================
# I/O HELPERS
# =====================================================
def atomic_to_csv(df: pd.DataFrame, path: str):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    dir_name = os.path.dirname(path) or "."
    fd, tmp_path = tempfile.mkstemp(prefix="tmp_", suffix=".csv", dir=dir_name)
    os.close(fd)
    try:
        df.to_csv(tmp_path, index=False)
        os.replace(tmp_path, path)
    finally:
        try:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)
        except Exception:
            pass


def read_shared_feature_list(shared_path: str | None) -> list[str]:
    if not shared_path or not os.path.exists(shared_path):
        return []
    try:
        s = pd.read_csv(shared_path)
        if "feature" not in s.columns:
            return []
        return [str(v) for v in s["feature"].dropna().tolist()]
    except Exception:
        return []


def list_pollutant_files(pollutant_dir: str) -> list[str]:
    """
    Neem alleen pollutant-observaties mee.
    Sluit rapport- en helperbestanden uit die script 2 nu ook wegschrijft.
    """
    files = sorted(glob.glob(os.path.join(pollutant_dir, "*.csv")))
    excluded_exact = {
        "balancing_report_summary.csv",
        "balancing_report_by_country.csv",
    }
    excluded_prefixes = ("features_", "all_results", "feature_importance")

    keep = []
    for p in files:
        b = os.path.basename(p)
        if b in excluded_exact:
            continue
        if any(b.startswith(pref) for pref in excluded_prefixes):
            continue
        keep.append(p)
    return keep


# =====================================================
# FEATURES + JOIN
# =====================================================
def load_features(features_path: str, shared_features_path: str | None = None):
    if not os.path.exists(features_path):
        raise FileNotFoundError(f"Features-file niet gevonden: {features_path}")

    df = pd.read_csv(features_path)
    df.columns = df.columns.str.strip()
    df = df.loc[:, ~df.columns.duplicated()]

    if "hydrobasin_level12" not in df.columns:
        raise ValueError("Features-file mist kolom 'hydrobasin_level12'.")

    # Optioneel: forceer exact modelready shared lijst
    shared_features = read_shared_feature_list(shared_features_path)
    if shared_features:
        keep_cols = [c for c in ["hydrobasin_level12", "HYBAS_ID"] if c in df.columns]
        keep_cols += [c for c in shared_features if c in df.columns]
        df = df[keep_cols].copy()

    # 1 rij per basin key
    df["hydrobasin_level12"] = df["hydrobasin_level12"].astype("string").str.replace(r"\.0$", "", regex=True).str.strip()
    df = df.dropna(subset=["hydrobasin_level12"]).drop_duplicates(subset="hydrobasin_level12", keep="first").reset_index(drop=True)

    monthly_cols = [c for c in df.columns if re.search(r"_s(0[1-9]|1[0-2])$", c)]
    monthly_bases = sorted({c.rsplit("_", 1)[0] for c in monthly_cols})

    id_cols = {"hydrobasin_level12", "HYBAS_ID"}
    static_cols = [c for c in df.columns if c not in id_cols and c not in monthly_cols]

    print(f"✅ Features loaded: rows={len(df):,}, cols={len(df.columns)}")
    print(f"   Static cols={len(static_cols)}, Monthly cols={len(monthly_cols)}, Monthly bases={len(monthly_bases)}")

    return df, static_cols, monthly_cols, monthly_bases


def build_joined_features(obs_path: str,
                          df_feats: pd.DataFrame,
                          static_cols: list[str],
                          monthly_cols: list[str],
                          analysis_mode: str) -> pd.DataFrame:
    obs = pd.read_csv(obs_path)

    required = {"wqms_id", "obs", "month", "hydrobasin_level12"}
    missing = required - set(obs.columns)
    if missing:
        raise ValueError(f"Observations-file mist verplichte kolommen: {missing}")

    obs["hydrobasin_level12"] = obs["hydrobasin_level12"].astype("string").str.replace(r"\.0$", "", regex=True).str.strip()
    obs = obs[obs["hydrobasin_level12"].notna()].copy()

    # Alleen valide maanden
    obs["month"] = pd.to_numeric(obs["month"], errors="coerce")
    obs = obs[obs["month"].between(1, 12, inclusive="both")].copy()
    obs["month"] = obs["month"].astype(int)

    # Alleen basins waar features voor bestaan
    obs = obs[obs["hydrobasin_level12"].isin(df_feats["hydrobasin_level12"])].copy()
    if obs.empty:
        return obs

    # static merge
    overlap = set(obs.columns) & set(static_cols)
    static_no_overlap = [c for c in static_cols if c not in overlap]

    base = obs.merge(
        df_feats[["hydrobasin_level12"] + static_no_overlap],
        on="hydrobasin_level12",
        how="left",
        validate="m:1"
    )

    # maandmapping: var_sMM -> var
    if monthly_cols:
        rows = []
        for m in range(1, 13):
            part = base.loc[base["month"] == m].copy()
            if part.empty:
                continue
            suffix = f"_s{m:02d}"
            mcols = [c for c in monthly_cols if c.endswith(suffix)]
            if not mcols:
                rows.append(part)
                continue

            feats_m = df_feats[["hydrobasin_level12"] + mcols].copy()
            feats_m = feats_m.rename(columns={c: c.rsplit("_", 1)[0] for c in mcols})

            joined = part.merge(feats_m, on="hydrobasin_level12", how="left", validate="m:1")
            rows.append(joined)

        df_full = pd.concat(rows, ignore_index=True) if rows else base.copy()

        # verwijder overgebleven _sMM kolommen
        drop_mm = [c for c in df_full.columns if re.search(r"_s(0[1-9]|1[0-2])$", c)]
        df_full = df_full.drop(columns=drop_mm, errors="ignore")
    else:
        df_full = base

    # Geofilter voor EU-mode
    if analysis_mode == "EU_train_NL_test" and COUNTRY_FIELD in df_full.columns:
        before = len(df_full)
        df_full = df_full[df_full[COUNTRY_FIELD].isin(EUROPE_COUNTRIES)].copy()
        print(f"EU-filter: {before:,} -> {len(df_full):,}")

    # Kolomnamen opschonen
    df_full.columns = df_full.columns.str.strip()
    df_full = df_full.loc[:, ~df_full.columns.duplicated()]

    return df_full


# =====================================================
# DATA PREP
# =====================================================
def prepare_data(df_full: pd.DataFrame):
    if df_full is None or df_full.empty:
        return None, None, None, []

    if "obs" not in df_full.columns:
        raise ValueError("Kolom 'obs' ontbreekt na join.")

    df = df_full.copy()
    df["obs"] = pd.to_numeric(df["obs"], errors="coerce")

    # Alleen model-features (numeric), zonder identifiers/topologie/categoriecodes.
    exclude = {
        "obs", "variable", "unit", "dates", "year", "year_month", "month",
        "wqms_id", "hydrobasin_level12", "HYBAS_ID", COUNTRY_FIELD,
    }

    feature_cols = [c for c in df.columns if c not in exclude and is_model_predictor_column(c)]
    feature_cols = [c for c in feature_cols if pd.api.types.is_numeric_dtype(df[c])]

    if not feature_cols:
        return None, None, None, []

    mask_good = (~df[feature_cols].isna().all(axis=1)) & (~df["obs"].isna())
    clean = df.loc[mask_good].reset_index(drop=True)
    if clean.empty:
        return None, None, None, feature_cols

    X = clean[feature_cols].copy().replace([np.inf, -np.inf], np.nan)
    miss_before = float(X.isna().mean().mean()) * 100.0

    # 1) Group-aware imputatie (van fijn -> grover)
    # Deze volgorde behoudt zoveel mogelijk hydrologische/regionale context.
    group_order = ["hydrobasin_level12", "MAIN_BAS", COUNTRY_FIELD]
    used_groups = []
    X_imp = X.copy()
    for g in group_order:
        if g in clean.columns:
            grp_med = X_imp.groupby(clean[g]).transform("median")
            X_imp = X_imp.fillna(grp_med)
            used_groups.append(g)

    # 2) Globale median fallback
    med = X_imp.median(numeric_only=True)
    X_imp = X_imp.fillna(med).fillna(0)

    miss_after = float(X_imp.isna().mean().mean()) * 100.0
    print(f"Imputatie: missings {miss_before:.2f}% -> {miss_after:.2f}% | groups={used_groups if used_groups else ['none']}")

    X = X_imp.astype(np.float32)

    y = clean["obs"].astype(np.float32).to_numpy()

    return clean, X, y, feature_cols


# =====================================================
# CV UTILS
# =====================================================
def compute_feature_importance(model, X_test, y_test, feature_cols, scoring="r2", n_repeats=5):
    res = permutation_importance(
        model, X_test, y_test,
        n_repeats=n_repeats,
        scoring=scoring,
        random_state=SEED
    )
    return pd.DataFrame({
        "Feature": feature_cols,
        "Feature_label": [feature_label(c) for c in feature_cols],
        "Importance": res.importances_mean.astype(np.float32),
        "Importance_std": res.importances_std.astype(np.float32),
    })


def build_grouped_kfold_splits(X, y, clean, group_series, all_idx, n_splits, min_group_size=1, restrict_test_mask=None):
    if restrict_test_mask is not None:
        vc = group_series[restrict_test_mask].value_counts()
    else:
        vc = group_series.value_counts()

    eligible_groups = vc[vc >= min_group_size].index
    if len(eligible_groups) < 2:
        raise ValueError(f"Te weinig geschikte groepen (>= {min_group_size})")

    n_splits_eff = min(n_splits, max(2, len(eligible_groups)))
    gkf = GroupKFold(n_splits=n_splits_eff)

    splits = []
    fold_keys = []

    if restrict_test_mask is None:
        mask = clean.index.isin(all_idx)
        X_use = X[mask]
        y_use = y[mask]
        groups_use = group_series[mask]

        for _, test_pos in gkf.split(X_use, y_use, groups=groups_use):
            idx_all = clean.index[mask].to_numpy()
            test_idx = idx_all[test_pos]
            keep = np.isin(group_series.loc[test_idx].to_numpy(), eligible_groups.to_numpy())
            test_idx = test_idx[keep]
            train_idx = np.setdiff1d(all_idx, test_idx, assume_unique=False)
            splits.append((train_idx, test_idx))
            fold_keys.append(group_series.loc[test_idx].unique().tolist())
    else:
        idx_restricted = clean.index[restrict_test_mask].to_numpy()
        groups_use = group_series[restrict_test_mask]
        is_eligible = groups_use.isin(eligible_groups)

        idx_restricted = idx_restricted[is_eligible.to_numpy()]
        X_use = X[restrict_test_mask][is_eligible.to_numpy()]
        y_use = y[restrict_test_mask][is_eligible.to_numpy()]
        groups_use = groups_use[is_eligible]

        for _, test_pos in gkf.split(X_use, y_use, groups=groups_use):
            test_idx = idx_restricted[test_pos]
            train_idx = np.setdiff1d(all_idx, test_idx, assume_unique=False)
            splits.append((train_idx, test_idx))
            fold_keys.append(group_series.loc[test_idx].unique().tolist())

    return splits, fold_keys


def run_cv_gpu_only(X, y, feature_cols, clean,
                    cv_type="Random CV", group_col=None, n_splits=5,
                    importance_on_cv=("Random CV", "Station CV", "Country CV", "Basin CV"),
                    n_repeats=5, scoring="r2",
                    restrict_test_to_country=None,
                    exclude_country_from_train=None,
                    min_group_size=5):

    if set_global_output_type is not None:
        try:
            set_global_output_type("numpy")
        except Exception:
            pass

    X_gpu = cudf.DataFrame(X, columns=feature_cols)
    models = {
        "RF": lambda: cuRF(n_estimators=200, random_state=SEED, n_streams=1)
    }

    all_idx = np.arange(len(X))
    c_idx = None

    if restrict_test_to_country is not None:
        if COUNTRY_FIELD not in clean.columns:
            raise ValueError(f"Kolom '{COUNTRY_FIELD}' ontbreekt voor NL-testrestrictie")
        c_mask = (clean[COUNTRY_FIELD] == restrict_test_to_country)
        c_idx = np.where(c_mask.values)[0]
        if len(c_idx) == 0:
            raise ValueError(f"Geen rijen voor testland '{restrict_test_to_country}'")

    # splits
    if cv_type == "Random CV":
        if c_idx is None:
            kf = KFold(n_splits=min(n_splits, max(2, len(all_idx))), shuffle=True, random_state=SEED)
            splits = list(kf.split(X))
            fold_keys = list(range(1, len(splits) + 1))
        else:
            n_eff = min(n_splits, max(2, len(c_idx)))
            kf = KFold(n_splits=n_eff, shuffle=True, random_state=SEED)
            splits, fold_keys = [], list(range(1, n_eff + 1))
            for _, test_pos in kf.split(c_idx):
                test_idx = c_idx[test_pos]
                train_idx = np.setdiff1d(all_idx, test_idx, assume_unique=False)
                splits.append((train_idx, test_idx))

    elif cv_type == "Station CV":
        if "wqms_id" not in clean.columns:
            raise ValueError("Station CV vereist kolom 'wqms_id'")

        if c_idx is None:
            groups = clean["wqms_id"]
            n_eff = min(n_splits, max(2, len(groups.unique())))
            gkf = GroupKFold(n_splits=n_eff)
            splits = list(gkf.split(X, y, groups=groups))
            fold_keys = [clean.loc[test_idx, "wqms_id"].unique().tolist() for _, test_idx in splits]
        else:
            groups_c = clean.loc[c_idx, "wqms_id"]
            n_eff = min(n_splits, max(2, len(groups_c.unique())))
            gkf = GroupKFold(n_splits=n_eff)
            splits, fold_keys = [], []
            for _, test_pos in gkf.split(c_idx, y[c_idx], groups=groups_c):
                test_idx = c_idx[test_pos]
                train_idx = np.setdiff1d(all_idx, test_idx, assume_unique=False)
                splits.append((train_idx, test_idx))
                fold_keys.append(clean.loc[test_idx, "wqms_id"].unique().tolist())

    elif cv_type == "Country CV":
        groups = clean[group_col] if group_col else clean[COUNTRY_FIELD]
        restrict_mask = None if c_idx is None else clean.index.isin(c_idx)
        splits, fold_keys = build_grouped_kfold_splits(
            X=X, y=y, clean=clean, group_series=groups, all_idx=all_idx,
            n_splits=n_splits, min_group_size=min_group_size, restrict_test_mask=restrict_mask
        )

    elif cv_type == "Basin CV":
        groups = clean["hydrobasin_level12"]
        restrict_mask = None if c_idx is None else clean.index.isin(c_idx)
        splits, fold_keys = build_grouped_kfold_splits(
            X=X, y=y, clean=clean, group_series=groups, all_idx=all_idx,
            n_splits=n_splits, min_group_size=min_group_size, restrict_test_mask=restrict_mask
        )

    else:
        raise ValueError(f"Onbekende cv_type: {cv_type}")

    perf_rows, fi_rows = [], []
    pollutant = clean["variable"].iat[0] if ("variable" in clean.columns and len(clean)) else "unknown"

    fold = 1
    for fold_label, (train_idx, test_idx) in zip(fold_keys, splits):
        if len(test_idx) < 10:
            continue

        if exclude_country_from_train is not None and COUNTRY_FIELD in clean.columns:
            keep_train = (clean.iloc[train_idx][COUNTRY_FIELD] != exclude_country_from_train).values
            train_idx = train_idx[keep_train]

        if DEBUG_FOLD_COUNTS and restrict_test_to_country is not None and COUNTRY_FIELD in clean.columns:
            n_train = int((clean.iloc[train_idx][COUNTRY_FIELD] == restrict_test_to_country).sum())
            n_test = int((clean.iloc[test_idx][COUNTRY_FIELD] == restrict_test_to_country).sum())
            print(f"  Fold {fold}: NL in train={n_train}, NL in test={n_test}")

        Xte = X[test_idx]
        yte = y[test_idx]

        Xtr_gpu = X_gpu.iloc[train_idx]
        Xte_gpu = X_gpu.iloc[test_idx]
        ytr_gpu = cudf.Series(y[train_idx])

        for model_name, model_builder in models.items():
            model = model_builder()
            model.fit(Xtr_gpu, ytr_gpu)
            pred = np.asarray(model.predict(Xte_gpu))

            rmse, nrmse_mean, nrmse_range, nrmse_std = compute_rmse_and_nrmse(yte, pred)
            r2 = float(r2_score(yte, pred))

            if restrict_test_to_country is None:
                cv_label = cv_type
            else:
                suffix = "NL test; NL excluded" if exclude_country_from_train == restrict_test_to_country else "NL test; NL allowed"
                cv_label = f"{cv_type} ({suffix})"

            perf_rows.append({
                "Fold": fold,
                "Model": model_name,
                "Variable": pollutant,
                "CV_type": cv_label,
                "Obs.": int(len(yte)),
                "R2": r2,
                "R2 (%)": r2 * 100.0,
                "RMSE": rmse,
                "NRMSE_mean": nrmse_mean,
                "NRMSE_range": nrmse_range,
                "NRMSE_std": nrmse_std,
                "Country": restrict_test_to_country if restrict_test_to_country else (fold_label if cv_type == "Country CV" else None),
                "Basin": fold_label if cv_type == "Basin CV" else None,
                "wqms_id": fold_label if cv_type == "Station CV" else None,
            })

            if cv_type in importance_on_cv:
                fi_df = compute_feature_importance(
                    model=model,
                    X_test=Xte,
                    y_test=yte,
                    feature_cols=feature_cols,
                    scoring=scoring,
                    n_repeats=n_repeats,
                )
                fi_df["Fold"] = fold
                fi_df["CV_type"] = cv_label
                fi_df["Model"] = model_name
                fi_df["Variable"] = pollutant
                fi_df["Obs."] = int(len(yte))
                fi_rows.append(fi_df)

        fold += 1

    perf_df = pd.DataFrame(perf_rows)
    fi_all = pd.concat(fi_rows, ignore_index=True) if fi_rows else pd.DataFrame()
    return perf_df, fi_all


# =====================================================
# MODE RUNNER
# =====================================================
def update_fi_summary(fi_path: str, fi_summary_path: str):
    if not os.path.exists(fi_path):
        return
    fi = pd.read_csv(fi_path)
    if fi.empty:
        return
    if "Feature_label" not in fi.columns:
        fi["Feature_label"] = fi["Feature"].map(feature_label)

    summary = (fi.groupby(["Variable", "CV_type", "Feature", "Feature_label"], as_index=False)
                 .agg(Importance_mean=("Importance", "mean"),
                      Importance_std=("Importance", "std"),
                      Obs_sum=("Obs.", "sum")))
    atomic_to_csv(summary, fi_summary_path)


def run_mode(mode_name: str,
             pollutant_dir: str,
             features_path_world: str,
             features_path_europe: str,
             shared_features_world: str | None,
             shared_features_europe: str | None,
             output_base_world: str,
             output_base_eu_nl: str,
             output_files: str):

    if mode_name == "EU_train_NL_test":
        features_path = features_path_europe
        shared_features_path = shared_features_europe
        output_dir = output_base_eu_nl
    elif mode_name == "WORLD_all":
        features_path = features_path_world
        shared_features_path = shared_features_world
        output_dir = output_base_world
    else:
        raise ValueError(f"Onbekende mode: {mode_name}")

    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_files, exist_ok=True)

    results_path = os.path.join(output_dir, "all_results.csv")
    fi_path = os.path.join(output_dir, "feature_importance.csv")
    fi_summary_path = os.path.join(output_dir, "feature_importance_summary.csv")

    print("\n" + "=" * 80)
    print(f"MODE: {mode_name}")
    print("=" * 80)

    pollutant_files = list_pollutant_files(pollutant_dir)
    print(f"Gevonden pollutant-files: {len(pollutant_files)}")

    df_feats, static_cols, monthly_cols, _monthly_bases = load_features(
        features_path=features_path,
        shared_features_path=shared_features_path
    )

    processed_variables = set()
    if os.path.exists(results_path):
        try:
            old = pd.read_csv(results_path)
            if "Variable" in old.columns:
                processed_variables = set(old["Variable"].dropna().astype(str).unique())
            print(f"✅ {len(processed_variables)} variabelen al aanwezig in {mode_name}; skip actief")
        except Exception as e:
            print(f"⚠️ Kon bestaande resultaten niet lezen ({e})")

    last_feature_cols = []

    for path in pollutant_files:
        file_name = os.path.basename(path)
        variable = os.path.splitext(file_name)[0]

        if variable in processed_variables:
            print(f"⏩ Skip {variable} (al aanwezig)")
            continue

        try:
            print(f"\n>>> Processing {file_name} ({mode_name})")
            df_full = build_joined_features(
                obs_path=path,
                df_feats=df_feats,
                static_cols=static_cols,
                monthly_cols=monthly_cols,
                analysis_mode=mode_name,
            )
            if df_full is None or df_full.empty:
                print("  (Geen rijen na join)")
                continue

            clean, X_df, y, feature_cols = prepare_data(df_full)
            if clean is None:
                print("  (Geen valide data na prepare_data)")
                continue

            last_feature_cols = feature_cols
            X = X_df.to_numpy(dtype=np.float32)

            # Debug subset
            try:
                debug_name = file_name.replace(".csv", f"_{mode_name}_rf_input.csv")
                X_df.head(1000).to_csv(os.path.join(output_files, debug_name), index=False)
            except Exception as e:
                print(f"⚠️ Debug feature-export mislukt: {e}")

            perf_frames, fi_frames = [], []

            if mode_name == "EU_train_NL_test":
                exclude_country = NL_NAME if STRICT_TRANSFER else None
                label_train = "EU excl. NL" if STRICT_TRANSFER else "EU incl. NL (except test fold)"

                print(f"  Random CV (test=NL fold, train={label_train})")
                perf, fi = run_cv_gpu_only(
                    X, y, feature_cols, clean,
                    cv_type="Random CV",
                    n_splits=N_SPLITS_RANDOM,
                    importance_on_cv=("Random CV", "Station CV", "Basin CV"),
                    restrict_test_to_country=NL_NAME,
                    exclude_country_from_train=exclude_country,
                )
                perf_frames.append(perf); fi_frames.append(fi)

                print(f"  Station CV (test=NL fold, train={label_train})")
                perf, fi = run_cv_gpu_only(
                    X, y, feature_cols, clean,
                    cv_type="Station CV",
                    n_splits=N_SPLITS_STATION,
                    importance_on_cv=("Random CV", "Station CV", "Basin CV"),
                    restrict_test_to_country=NL_NAME,
                    exclude_country_from_train=exclude_country,
                )
                perf_frames.append(perf); fi_frames.append(fi)

                print(f"  Basin CV (test=NL fold, train={label_train})")
                perf, fi = run_cv_gpu_only(
                    X, y, feature_cols, clean,
                    cv_type="Basin CV",
                    n_splits=N_SPLITS_BASIN,
                    importance_on_cv=("Random CV", "Station CV", "Basin CV"),
                    restrict_test_to_country=NL_NAME,
                    exclude_country_from_train=exclude_country,
                    min_group_size=MIN_GROUP_SIZE_BASIN,
                )
                perf_frames.append(perf); fi_frames.append(fi)

            elif mode_name == "WORLD_all":
                print("  Random CV (WORLD)")
                perf, fi = run_cv_gpu_only(
                    X, y, feature_cols, clean,
                    cv_type="Random CV",
                    n_splits=N_SPLITS_RANDOM,
                    importance_on_cv=("Random CV", "Station CV", "Country CV", "Basin CV"),
                )
                perf_frames.append(perf); fi_frames.append(fi)

                print("  Station CV (WORLD)")
                perf, fi = run_cv_gpu_only(
                    X, y, feature_cols, clean,
                    cv_type="Station CV",
                    n_splits=N_SPLITS_STATION,
                    importance_on_cv=("Random CV", "Station CV", "Country CV", "Basin CV"),
                )
                perf_frames.append(perf); fi_frames.append(fi)

                if COUNTRY_FIELD in clean.columns and clean[COUNTRY_FIELD].nunique(dropna=True) > 1:
                    print("  Country CV (WORLD)")
                    perf, fi = run_cv_gpu_only(
                        X, y, feature_cols, clean,
                        cv_type="Country CV",
                        group_col=COUNTRY_FIELD,
                        n_splits=N_SPLITS_COUNTRY,
                        importance_on_cv=("Random CV", "Station CV", "Country CV", "Basin CV"),
                        min_group_size=MIN_GROUP_SIZE_COUNTRY,
                    )
                    perf_frames.append(perf); fi_frames.append(fi)

                print("  Basin CV (WORLD)")
                perf, fi = run_cv_gpu_only(
                    X, y, feature_cols, clean,
                    cv_type="Basin CV",
                    n_splits=N_SPLITS_BASIN,
                    importance_on_cv=("Random CV", "Station CV", "Country CV", "Basin CV"),
                    min_group_size=MIN_GROUP_SIZE_BASIN,
                )
                perf_frames.append(perf); fi_frames.append(fi)

            # Incrementele opslag results
            perf_concat = pd.concat([p for p in perf_frames if p is not None and not p.empty], ignore_index=True) if perf_frames else pd.DataFrame()
            if not perf_concat.empty:
                perf_concat["File"] = file_name
                if os.path.exists(results_path):
                    perf_concat.to_csv(results_path, mode="a", header=False, index=False)
                else:
                    perf_concat.to_csv(results_path, index=False)
                print(f"✅ all_results append: {results_path}")

            # Incrementele opslag FI
            fi_concat = pd.concat([f for f in fi_frames if f is not None and not f.empty], ignore_index=True) if fi_frames else pd.DataFrame()
            if not fi_concat.empty:
                fi_concat["File"] = file_name
                if os.path.exists(fi_path):
                    fi_concat.to_csv(fi_path, mode="a", header=False, index=False)
                else:
                    fi_concat.to_csv(fi_path, index=False)
                print(f"✅ feature_importance append: {fi_path}")

                # Belangrijk: ook summary tussentijds verversen (crash-safe)
                update_fi_summary(fi_path, fi_summary_path)

            processed_variables.add(variable)

        except ValueError as e:
            print(f"❌ ValueError bij {file_name}: {e}")
            continue
        except Exception as e:
            print(f"❌ Onverwachte fout bij {file_name}: {e}")
            continue

    # Finale check/samenvatting
    final_results = pd.read_csv(results_path) if os.path.exists(results_path) else pd.DataFrame()
    final_fi_summary = pd.read_csv(fi_summary_path) if os.path.exists(fi_summary_path) else pd.DataFrame()

    print(f"\n✅ Mode klaar: {mode_name}")
    print(f"   all_results rows: {len(final_results):,}")
    print(f"   FI summary rows: {len(final_fi_summary):,}")

    return final_results, final_fi_summary, last_feature_cols


# =====================================================
# MAIN
# =====================================================
def main():
    # Paden afgestemd op script 1/2 in T2-output structuur
    pollutant_dir = "/content/drive/MyDrive/SamuelRebel_thesis/T2/T3/output/observations/mean_test/"

    features_path_europe = "/content/drive/MyDrive/SamuelRebel_thesis/T2/T3/output/features/features_modelready_basin_europe.csv"
    features_path_world = "/content/drive/MyDrive/SamuelRebel_thesis/T2/T3/output/features/features_modelready_basin_global.csv"

    shared_features_europe = "/content/drive/MyDrive/SamuelRebel_thesis/T2/T3/output/features/features_modelready_shared_columns_europe.csv"
    shared_features_world = "/content/drive/MyDrive/SamuelRebel_thesis/T2/T3/output/features/features_modelready_shared_columns_global.csv"

    output_base_eu_nl = "/content/drive/MyDrive/SamuelRebel_thesis/T2/T3/output/results_ML/all_pollutants/europe_nederland/"
    output_base_world = "/content/drive/MyDrive/SamuelRebel_thesis/T2/T3/output/results_ML/all_pollutants/world/"

    output_files = "/content/drive/MyDrive/SamuelRebel_thesis/T2/T3/output/ML_files/"

    run_preflight_checks(
        pollutant_dir=pollutant_dir,
        features_path_europe=features_path_europe,
        features_path_world=features_path_world,
        shared_features_europe=shared_features_europe,
        shared_features_world=shared_features_world,
        output_base_eu_nl=output_base_eu_nl,
        output_base_world=output_base_world,
        output_files=output_files,
    )

    mode_outputs = {}
    for mode_name in RUN_MODES:  # blijft expliciet EU -> WORLD
        out_results, out_fi_summary, out_feature_cols = run_mode(
            mode_name=mode_name,
            pollutant_dir=pollutant_dir,
            features_path_world=features_path_world,
            features_path_europe=features_path_europe,
            shared_features_world=shared_features_world,
            shared_features_europe=shared_features_europe,
            output_base_world=output_base_world,
            output_base_eu_nl=output_base_eu_nl,
            output_files=output_files,
        )
        mode_outputs[mode_name] = {
            "results_df": out_results,
            "fi_summary_df": out_fi_summary,
            "feature_cols": out_feature_cols,
        }

    return mode_outputs


mode_outputs = main()

for mode_name, out in mode_outputs.items():
    results_df = out["results_df"]
    fi_summary_df = out["fi_summary_df"]
    feat_cols = out["feature_cols"]

    print("\n" + "-" * 80)
    print(f"MODE OUTPUT: {mode_name}")
    print("-" * 80)
    print(f"Feature count used: {len(feat_cols)}")

    if results_df is not None and not results_df.empty:
        print("Performance sample:")
        print(results_df.head())
    else:
        print("Geen performance-resultaten")

    if fi_summary_df is not None and not fi_summary_df.empty:
        print("\nFI summary sample:")
        print(fi_summary_df.head())
    else:
        print("\nGeen FI-samenvatting")